version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: npm i
      - run: npm test
  build_image:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: docker build -t hello-node .

workflows:
  hello-node:
    jobs:
      - lint
      - build_image:
          requires: ['lint']

