version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  lint:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: npm i
      - run: npm test
  build_image:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t braxnu/hello-node .
      - run: echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker push braxnu/hello-node
  update_stack:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - run: aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name hello-node
      - run: kubectl set image deployment.apps/${DEPLOYMENT_NAME} hello-node=braxnu/hello-node --server ${K8_SERVER}
      - run: kubectl rollout restart deployment.apps/${DEPLOYMENT_NAME} --server ${K8_SERVER}

workflows:
  hello-node:
    jobs:
      - lint
      - build_image:
          requires: ['lint']
          filters:
            branches:
              only: master
      - update_stack:
          requires: ['build_image']
